mysqldb:
  image: mysql
  container_name: mysqldb
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - "3306:3306"
tomcat:
  build: .
  container_name: tomcat
  ports:
    - "8080:8080"
  links:
    - mysqldb
