#!/bin/bash

input=$1

make clean -sC ./src
make -sC ./src

if [[ -n "$input" ]]; then
    make run INPUT=../$input -sC ./src
else
    make run -sC ./src
fi

echo "***************************************************output/stacktrace.txt"
cat output/stacktrace.txt
